
version: '2'

services:
  oauth2-server:
    image: oauth2-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000